# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'monitoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10monitoring.proto\x12\x0eLatencyMonitor\"\x0e\n\x0c\x45mptyRequest\"^\n\nPingUpdate\x12\x13\n\x0btarget_name\x18\x01 \x01(\t\x12\x12\n\nlatency_ms\x18\x02 \x01(\x05\x12\x14\n\x0cstatus_color\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t2_\n\x0eNetworkMonitor\x12M\n\x0fStreamLatencies\x12\x1c.LatencyMonitor.EmptyRequest\x1a\x1a.LatencyMonitor.PingUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=36
  _globals['_EMPTYREQUEST']._serialized_end=50
  _globals['_PINGUPDATE']._serialized_start=52
  _globals['_PINGUPDATE']._serialized_end=146
  _globals['_NETWORKMONITOR']._serialized_start=148
  _globals['_NETWORKMONITOR']._serialized_end=243
# @@protoc_insertion_point(module_scope)
